twiddit/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('', views.PostListView.as_view(), name='blog-home'),
    path('home/', views.PostListView.as_view(), name='blog-home'),
    path('user/<str:username>/', views.UserPostListView.as_view(), name='user-posts'),
    path('about/', views.about, name='blog-about'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('post/<slug:slug>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('upvote/', views.upvote_post, name='upvote-post'),
    path('downvote/', views.downvote_post, name='downvote-post'),
    # path('?search=<str:query>', views.search_view, name='search-results'),
]

twiddit/twiddit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path('', include('users.urls')),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='users/logout.html'),
         name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', # Needs these URL parameters
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', include(arg=('users.urls', 'users'), namespace='users')),
    path('', include(arg=('blog.urls', 'blog'), namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twiddit/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('user/<str:username>/follow/', views.follow_info, name='follow-info'),
    path('user/<str:username>/follow-toggle/', views.follow_toggle, name='follow-toggle'),
]

twiddit/blog/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
# from django.utils import timezone
from . import utils
from account.models import Account


class Post(models.Model):
    author = models.ForeignKey(to=Account, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    upvotes = models.ManyToManyField(to=Account, related_name='upvotes', blank=True)
    downvotes = models.ManyToManyField(to=Account, related_name='downvotes', blank=True)
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    
    class Meta:
        ordering = ['-date_posted']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse(viewname='post-detail', kwargs={'slug': self.slug})
    
    @property
    def total_upvotes(self):
        return self.upvotes.count()
    
    @property
    def total_downvotes(self):
        return self.downvotes.count()


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = utils.unique_slug_generator(instance=instance)

pre_save.connect(receiver=slug_generator, sender=Post)


class Comment(models.Model):
    author = models.ForeignKey(to=Account, on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['date_posted']
    
    def __str__(self):
        return self.content
    
    def get_absolute_url(self):
        return reverse(viewname='post-detail', kwargs={'slug': self.slug})

twiddit/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', ) # 'post' and 'author' should not be in this form


class SearchForm(forms.Form):
    search_string = forms.CharField(max_length=200)

twiddit/blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
# from django.utils import simplejson
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from .filters import SearchFilter
from .forms import CommentForm, SearchForm
from .models import Post, Comment
from account.models import Account


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home.html' # Format: <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 10

    def get_queryset(self):
        """ Shows user's posts only if you're following them """
        user_account = Account.objects.filter(username=self.request.user).first()
        following_list = [following.get_following for following in user_account.following.all()]
        following_list.append(user_account) # Show posts of current user as well
        post_context = Post.objects.filter(author__in=following_list).order_by('-date_posted')
        # if 'search' not in self.request.GET:
        #     search_term = str(self.request.GET['search']).strip()
        #     user_search_tag = 'u/'
        #     user_search_tag_length = len(user_search_tag)
        #     if search_term[:user_search_tag_length] == user_search_tag:
        #         user_searched = search_term[user_search_tag_length:].replace(' ', '')
        #         user_searched = Account.objects.filter(username=user_searched).first()
        #         post_context = Post.objects.filter(author__in=[user_searched]).order_by('-date_posted')
        #     else:
        #         post_context = post_context.filter(Q(title__icontains=search_term) | Q(content__icontains=search_term))
        return post_context


class UserPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/user_posts.html' # Format: <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(klass=Account, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


@login_required
def post_detail(request, slug, *args, **kwargs):
    post = get_object_or_404(klass=Post, slug=slug, *args, **kwargs)
    comments = post.comments.order_by('date_posted')
    new_comment = None
    
    is_upvoted, is_downvoted = False, False
    if post.upvotes.filter(id=request.user.id).exists():
        is_upvoted = True
    if post.downvotes.filter(id=request.user.id).exists():
        is_downvoted = True

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request=request, message='Successfully posted the comment!')
        else:
            messages.warning(request=request, message='Could not post the comment!')
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'is_upvoted': is_upvoted,
        'is_downvoted': is_downvoted,
        'net_votes': post.total_upvotes - post.total_downvotes,
        'total_upvotes': post.total_upvotes,
        'total_downvotes': post.total_downvotes,
    }
    return render(request=request, template_name='blog/post_detail.html', context=context)


@login_required
def upvote_post(request, *args, **kwargs):
    post = get_object_or_404(klass=Post, id=request.POST.get('post_id'), *args, **kwargs)
    is_upvoted = False
    is_downvoted = False
    if post.upvotes.filter(id=request.user.id).exists():
        post.upvotes.remove(request.user)
        is_upvoted = False
    else:
        post.upvotes.add(request.user)
        is_upvoted = True
    return HttpResponseRedirect(redirect_to=post.get_absolute_url())


@login_required
def downvote_post(request, *args, **kwargs):
    post = get_object_or_404(klass=Post, id=request.POST.get('post_id'), *args, **kwargs)
    is_downvoted = False
    is_upvoted = False
    if post.downvotes.filter(id=request.user.id).exists():
        post.downvotes.remove(request.user)
        is_downvoted = False
    else:
        post.downvotes.add(request.user)
        is_downvoted = True
    return HttpResponseRedirect(redirect_to=post.get_absolute_url())


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/' # Redirects to home page on the successful deletion of the post

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form=form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    success_url = '/' # Redirects to home page on the successful deletion of the post

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form=form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/' # Redirects to home page on the successful deletion of the post

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    context = {'title': 'About'}
    return render(request=request, template_name='blog/about.html', context=context)

twiddit/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
<h2>About Page</h2>
{% endblock content %}

twiddit/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>Twiddit - {{ title }}</title>
    {% else %}
        <title>Twiddit</title>
    {% endif %}
</head>

<body>
    <header class="site-header">

      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Twiddit</a> <!-- Takes you to root page (without 'blog/home' in URL) -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'blog:user-posts' user.username %}">My Posts</a>
                <a class="nav-item nav-link" href="{% url 'profile' %}">{{ user.username }}'s Profile</a>
                <a class="nav-item nav-link" href="{% url 'users:follow-info' user.username %}">Follow Info</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    
    </header>

    <main role="main" class="container">
      <div class="row">
        
        <div class="col-md-8">

          <!-- Alert messages -->
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}

          {% block content %}{% endblock %}
        </div>

        <!-- Search bar -->
        <div class="col-md-4">
          <h4>Search bar</h4>
          <form class="form-inline my-2 my-lg-0">
            <input class="from-control mr-sm-2"
                   type="search"
                   placeholder="Search"
                   aria-label="Search"
                   name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>

        {% comment %} <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div> {% endcomment %}
      
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

twiddit/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">
              {{ post.date_posted | date:"Y, F d" }} at {{ post.date_posted | date:"H:i:s" }}
            </small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.slug %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        </article>
    {% endfor %}

    <!-- Pagination -->
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

{% endblock content %}

twiddit/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Confirm Delete</legend>
          <h2>Are you sure you want to delete the "{{ object.title }}" post?</h2>
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
          <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.slug %}" type="submit">Cancel</a>
        </div>
      </form>
    </div>
{% endblock content %}

twiddit/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <!-- Posts -->
    <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
          <small class="text-muted">
            {{ post.date_posted | date:"Y, F d" }} at {{ post.date_posted | date:"H:i:s" }}
            {% if post.date_updated != post.date_posted %}
              <div>
                (Last updated on {{ post.date_updated | date:"Y, F d" }} at {{ post.date_updated | date:"H:i:s" }})
              </div>
            {% endif %}
          </small>
          {% if post.author == user %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' post.slug %}">Update</a>
              <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' post.slug %}">Delete</a>
            </div>
          {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
    
    <div class="mr-3 mt-2">
      Votes: {{ net_votes }}
    </div>
    
    <form method="POST" action="{% url 'upvote-post' %}">
      {% csrf_token %}
      {% if is_upvoted %}
        <button class="btn btn-danger" type="submit" name="post_id" value="{{ post.id }}">
          Downvote
        </button>
      {% else %}
        <button class="btn btn-primary" type="submit" name="post_id" value="{{ post.id }}">
          Upvote
        </button>
      {% endif %}
    </form>

    <form method="POST" action="{% url 'downvote-post' %}">
      {% csrf_token %}
      {% if is_downvoted %}
        <button class="btn btn-primary" type="submit" name="post_id" value="{{ post.id }}">
          Upvote
        </button>
      {% else %}
        <button class="btn btn-danger" type="submit" name="post_id" value="{{ post.id }}">
          Downvote
        </button>
      {% endif %}
    </form>
    
    </article>

    <!-- Comments -->
    <div class="col-md-8 card mb-4 mt-3">
      <div class="card-body">
        {% if not comments %}
          <h3>No comments yet</h3>
        {% else %}
          <h3>{{ comments.count }} comments</h3>
        {% endif %}

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            <div class="article-metadata">
              <img class="rounded-circle comment-img" src="{{ comment.author.profile.image.url }}">
              <a class="mr-2" href="{% url 'user-posts' comment.author.username %}">
                {{ comment.author }}
              </a>
              <small class="text-muted font-weight-normal">
                {{ comment.date_posted | date:"Y, F d" }} at {{ comment.date_posted | date:"H:i:s" }}
              </small>
            </div>
          </p>
          {{ comment.content | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>

{% endblock content %}

twiddit/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Twiddit Post</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
      </form>
    </div>
{% endblock content %}

twiddit/blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block content %}
  {% if items %}
    <p class="search-count">
      Found <strong>{{ items.paginator.count }}</strong> result{{ items.paginator.count|pluralize }}
    </p>
    {% for i in items %}
      {{ i.path }}
    {% endfor %}
  {% elif request.GET.q %}
    <p class="search-no-results">
    No results for "<strong>{{ request.GET.q }}</strong>"
    </p>
  {% endif %}
{% endblock %}

twiddit/blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} (Total posts: {{ page_obj.paginator.count }})</h1>
    <h5 class="mb-3"><a href="{% url 'users:follow-info' view.kwargs.username %}">View {{ view.kwargs.username }}'s follower info</a></h5>
    {% for post in posts %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted|date:"Y, F d H:i:s" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.slug %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
        </article>
    {% endfor %}

    <!-- Pagination -->
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}

{% endblock content %}